import type { CSSProperties } from "react";

export const s: Record<string, CSSProperties> = {
  card: {
    border: "1px solid var(--border)",
    borderRadius: 12,
    padding: 18,
    background: "var(--bg-elevated)",
    display: "flex",
    flexDirection: "column",
    gap: 4,
    marginBottom: 20,
  },
  placeholder: {
    fontSize: 13.5,
    color: "var(--text-muted)",
    margin: 0,
  },
  reviewBand: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
    padding: "10px 0 12px",
    marginBottom: 4,
    borderBottom: "1px solid var(--border)",
  },
  reviewMeta: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 10,
    minHeight: 24,
  },
  verdictChip: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
  },
  verdictIconBox: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: 26,
    height: 26,
    borderRadius: 7,
    flexShrink: 0,
  },
  verdictLabel: {
    fontSize: 13.5,
    fontWeight: 700,
  },
  scoreCol: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 2,
    flexShrink: 0,
  },
  scoreLabel: {
    fontSize: 10,
    fontWeight: 700,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
  },
  cost: {
    fontSize: 12,
    color: "var(--text-secondary)",
    fontVariantNumeric: "tabular-nums",
  },
  focusLinkBtn: {
    appearance: "none",
    background: "none",
    border: "none",
    padding: 0,
    margin: 0,
    font: "inherit",
    fontSize: 13,
    color: "var(--accent-text)",
    cursor: "pointer",
    textAlign: "left",
  },
  headerActions: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  staleHint: {
    fontSize: 12.5,
    color: "var(--warn)",
    margin: "0 0 10px",
  },
  inlineError: {
    fontSize: 12.5,
    color: "var(--crit)",
    margin: "0 0 10px",
  },
  whatWhy: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
    fontSize: 14,
    color: "var(--text-primary)",
    marginBottom: 8,
  },
  riskLevelRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    marginBottom: 14,
  },
  riskLevelLabel: {
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: "0.05em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
  },
  section: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    marginTop: 10,
  },
  sectionLabel: {
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: "0.05em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
  },
  emptyNote: {
    fontSize: 13,
    color: "var(--text-muted)",
    margin: 0,
  },
  riskList: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    display: "flex",
    flexDirection: "column",
    gap: 10,
  },
  riskRow: {
    display: "flex",
    alignItems: "flex-start",
    gap: 10,
  },
  riskBody: {
    display: "flex",
    flexDirection: "column",
    gap: 3,
    flex: 1,
  },
  riskTitle: {
    fontSize: 13.5,
    fontWeight: 600,
    color: "var(--text-primary)",
  },
  riskExplanation: {
    fontSize: 13,
    color: "var(--text-secondary)",
    margin: 0,
    lineHeight: 1.5,
  },
  fileRefRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: 10,
    marginTop: 2,
  },
  fileRefPlain: {
    fontSize: 13,
    color: "var(--text-muted)",
  },
  focusList: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  focusRow: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "baseline",
    gap: 6,
    fontSize: 13,
  },
  focusReason: {
    color: "var(--text-secondary)",
  },
};
