import type { CSSProperties } from "react";

export const s: Record<string, CSSProperties> = {
  page: {
    display: "flex",
    flexDirection: "column",
    gap: 20,
    padding: "28px 32px",
    maxWidth: 1280,
    margin: "0 auto",
    width: "100%",
  },
  header: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 16,
    flexWrap: "wrap",
  },
  h1: { fontSize: 26, fontWeight: 700, margin: 0, color: "var(--text-primary)" },
  subtitle: { color: "var(--text-muted)", fontSize: 14, margin: "4px 0 0" },
  headerRight: { display: "flex", alignItems: "center", gap: 10 },
  syncIndicator: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    padding: "6px 12px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    fontSize: 13,
    color: "var(--text-secondary)",
    whiteSpace: "nowrap",
  },
  syncDot: {
    width: 7,
    height: 7,
    borderRadius: 99,
    background: "var(--ok)",
    boxShadow: "0 0 0 3px var(--ok-bg)",
  },
  filters: { display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap" },
  list: { display: "flex", flexDirection: "column", gap: 10 },
  tableWrap: {
    border: "1px solid var(--border)",
    borderRadius: 9,
    overflow: "hidden",
    background: "var(--bg-elevated)",
  },
  table: { width: "100%", borderCollapse: "collapse", fontSize: 13 },
  th: {
    textAlign: "left",
    padding: "10px 14px",
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    borderBottom: "1px solid var(--border)",
    whiteSpace: "nowrap",
  },
  td: {
    padding: "10px 14px",
    borderBottom: "1px solid var(--border)",
    color: "var(--text-secondary)",
    verticalAlign: "top",
  },
  tnum: { fontVariantNumeric: "tabular-nums" },
  prNumber: { color: "var(--text-primary)", fontWeight: 600 },
  prTitle: {
    color: "var(--text-muted)",
    fontSize: 12,
    marginTop: 2,
    maxWidth: 260,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  agentCell: { display: "flex", alignItems: "center", gap: 6, color: "var(--text-primary)" },
  traceLink: {
    background: "none",
    border: "none",
    padding: 0,
    fontSize: 13,
    fontWeight: 600,
    color: "var(--accent)",
    cursor: "pointer",
  },
  traceGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 16 },
  traceField: { display: "flex", flexDirection: "column", gap: 4 },
  traceLabel: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
  },
  traceValue: { fontSize: 14, color: "var(--text-primary)" },
  traceFooter: { marginTop: 20 },
  githubLink: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    padding: "9px 16px",
    borderRadius: 6,
    background: "var(--accent)",
    color: "#fff",
    fontSize: 13.5,
    fontWeight: 600,
    textDecoration: "none",
  },
};
