import { describe, it, expect } from "vitest";
import { parseYamlSafe, lintWorkflowYml } from "./lint";

// Mirrors the real generator output shape (server/src/modules/ci/generators/workflow.ts)
// so "clean" here means "what Preview actually renders", not an invented sample.
const CLEAN_WORKFLOW_YML = `# DevDigest CI Review — auto-generated by Export Wizard
name: DevDigest Review

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  contents: read
  pull-requests: write

jobs:
  devdigest-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Run DevDigest Review
        env:
          OPENROUTER_API_KEY: \${{ secrets.OPENROUTER_API_KEY }}
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
          POST_AS: github_review
        run: node .devdigest/runner/index.js

      - name: Upload review results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: devdigest-result
          path: devdigest-result.json
          if-no-files-found: ignore
`;

describe("parseYamlSafe", () => {
  it("returns ok:true for valid YAML", () => {
    expect(parseYamlSafe(CLEAN_WORKFLOW_YML)).toEqual({ ok: true });
  });

  it("returns ok:false with a message for YAML that fails to parse", () => {
    const result = parseYamlSafe("permissions:\n  contents: [read\n");
    expect(result.ok).toBe(false);
    if (!result.ok) {
      expect(typeof result.message).toBe("string");
      expect(result.message.length).toBeGreaterThan(0);
    }
  });
});

describe("lintWorkflowYml", () => {
  it("returns no warnings for the real generator output", () => {
    expect(lintWorkflowYml(CLEAN_WORKFLOW_YML)).toEqual([]);
  });

  it("warns when permissions are broader than contents:read + pull-requests:write", () => {
    const yml = CLEAN_WORKFLOW_YML.replace("contents: read", "contents: write");
    const warnings = lintWorkflowYml(yml);
    expect(warnings.some((w) => /permission/i.test(w))).toBe(true);
  });

  it("warns when a pull_request_target trigger is present", () => {
    const yml = CLEAN_WORKFLOW_YML.replace("on:\n  pull_request:", "on:\n  pull_request_target:");
    const warnings = lintWorkflowYml(yml);
    expect(warnings.some((w) => /pull_request_target/i.test(w))).toBe(true);
  });

  it("warns when a secret is hardcoded instead of ${{ secrets.* }}", () => {
    const yml = CLEAN_WORKFLOW_YML.replace(
      "OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}",
      "OPENROUTER_API_KEY: sk-hardcoded-example-123456"
    );
    const warnings = lintWorkflowYml(yml);
    expect(warnings.some((w) => /secret/i.test(w))).toBe(true);
  });

  it("warns when the runner invocation step is missing", () => {
    const yml = CLEAN_WORKFLOW_YML.replace("run: node .devdigest/runner/index.js", "run: echo noop");
    const warnings = lintWorkflowYml(yml);
    expect(warnings.some((w) => /runner/i.test(w))).toBe(true);
  });
});
